### ISSUE TITLE
CacheLock inactive even when `expire` is set

### ISSUE THREAD

**Issue by RomuloOliveira** [luizalabs/django-toolkit#13]
The current implementation of `CacheLock` always deactivate and delete the cache key, even when `expire` parameter is set.

Example:

``` python
with CacheLock(key=key, expire=99999999, cache_alias=cache_alias) as lock:
    pass

assert lock.cache.get(lock._key) is None
```

Is this the expected behaviour? The parameter `expire` should not be removed?

**Comment by renanivo** [comment]
I did not think about it when `CacheLock` was created. The way it is implemented `expire` has no use. But, I think there's still value for an `expire` parameter.

The way it is, the `CacheLock` is used to guarantee that just _one task is executed at a time_, but it fails to assert that a task is _executed only once_. So, if the visibility timeout expires at the same time as the task finishes, a task could be executed twice (or more times).

I think we could update the implementation of `CacheLock` to not delete the key when `expire` was given and the `__exit__` was called without an exception. That will prevent a task that is redelivered after a previous task is executed, but before it acknowledges its success.

**Comment by renanivo** [comment]
On a second thought, there's value to the `expire` parameter as it is. If a worker is killed in the middle of a task, the lock would be active forever without an expiration (although it can be configured in the [CACHES settings](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-CACHES)).

The feature I mentioned above can be implemented using another parameter, so I'm closing this issue. Feel free to reopen it if you have something new about it.
