### ISSUE TITLE
Django 1.10 Middlewares compatibility

### ISSUE THREAD

**Issue by renanivo** [luizalabs/django-toolkit#18]
The current [middlewares](django_toolkit/middlewares.py) are made for Django<=1.9. Django 1.0 has a [new interface for middlewares](https://docs.djangoproject.com/es/1.10/topics/http/middleware/), so we should start using the `django.utils.deprecation.MiddlewareMixin`.

**Comment by RomuloOliveira** [comment]
Fixed in #17
